# Generated by Django 3.0.5 on 2020-05-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ENAME', models.CharField(max_length=50)),
                ('AGE', models.IntegerField()),
                ('SALARY', models.IntegerField()),
                ('PHONE_NO', models.CharField(max_length=50)),
                ('CITY', models.CharField(max_length=50)),
                ('EMAIL', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Employee_Details',
                'verbose_name_plural': 'Employee_Detailss',
            },
        ),
    ]
